### ISSUE TITLE
Infinite Loop - Internal Compiler Error when mapping recursive structure

### ISSUE THREAD

**Issue by cyc1ingsir** [s0nicyouth/kmapper#17]
I just was hit by a 
```
* What went wrong:
Execution failed for task ':kspKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.compilerRunner.GradleCompilerRunnerWithWorkers$GradleKotlinCompilerWorkAction
   > Internal compiler error. See log for more details
```
error, basically caused by this infinite loop:
```
at com.syouth.kmapper.processor.convertors.CollectionTypeConverter.buildConversionStatement(CollectionTypeConverter.kt:35)
        at com.syouth.kmapper.processor.convertors.PojoClassTypeConverter.buildCodeBlockForDifferentTypes(PojoClassTypeConverter.kt:70)
        at com.syouth.kmapper.processor.convertors.PojoClassTypeConverter.buildConversionStatement(PojoClassTypeConverter.kt:43)
        at com.syouth.kmapper.processor.convertors.PojoClassTypeConverter.buildCodeBlockForDifferentTypes(PojoClassTypeConverter.kt:70)
        at com.syouth.kmapper.processor.convertors.PojoClassTypeConverter.buildConversionStatement(PojoClassTypeConverter.kt:43)
        at com.syouth.kmapper.processor.convertors.CollectionTypeConverter.buildCodeBlockForDataClasses(CollectionTypeConverter.kt:66)
        at com.syouth.kmapper.processor.convertors.CollectionTypeConverter.buildConversionStatement(CollectionTypeConverter.kt:35)
        at com.syouth.kmapper.processor.convertors.PojoClassTypeConverter.buildCodeBlockForDifferentTypes(PojoClassTypeConverter.kt:70)
        at com.syouth.kmapper.processor.convertors.PojoClassTypeConverter.buildConversionStatement(PojoClassTypeConverter.kt:43)
        at com.syouth.kmapper.processor.convertors.PojoClassTypeConverter.buildCodeBlockForDifferentTypes(PojoClassTypeConverter.kt:70)
        at com.syouth.kmapper.processor.convertors.PojoClassTypeConverter.buildConversionStatement(PojoClassTypeConverter.kt:43)
        at com.syouth.kmapper.processor.convertors.CollectionTypeConverter.buildCodeBlockForDataClasses(CollectionTypeConverter.kt:66)

```

The root cause was me needed to convert my uni directional relationship to a fully n:m relationship on the project I'm using kmapper for mapping. This is one of the mapper, being hit by the problem:
https://github.com/cetracker/cetrack-backend/blob/main/src/main/kotlin/de/cyclingsir/cetrack/part/storage/Mapper.kt#L32-L37

I setup a small example for demonstration purpose. It's all inside this commit:
https://github.com/cyc1ingsir/kmapper-examples/commit/592c99dfb22a8d3bdf7ed4a04e4f279284685c02

This also includes a workaround/solution(?) for the root cause:
Breaking the vicious circle with this mapping definition:
```kotlin
    fun map(dto: RecDtoPartA, @Bind relations: MutableList<AtoBRelationDomain>) : RecDomainPartA
```

and breaking up the mapping in smaller steps later on:
```kotlin
    val dtoPartB = findPartB()

    val partBMapper = PartBDto2DomainMapperImpl()
    val partAMapper = PartADto2DomainMapperImpl()

    val relationMapper = RelationDto2DomainMapperImpl()
    val domainRelations = dtoPartB.relations.map { relation ->
        relationMapper.map(
            relation,
            partAMapper.map(relation.partA, mutableListOf()),
            partBMapper.map(relation.partB, mutableListOf())
        )
    }
    val domainPartB = partBMapper.map(dtoPartB, domainRelations.toMutableList())
```

I wonder 
a) if there is a way for this library to discover this sort of error and bail out before being stopped, making it more robust/resilient on user errors?

and b) if there is a more elegant solution for handling the root cause?

**Comment by s0nicyouth** [comment]
@cyc1ingsir Hi, thanks for the report. The loop happens there because the definition of your data structure is recursive so the mapper goes into infinite recursion as well. I don't think that there's any general fix for this but errors like that can be detected and error message can be improved. Loop can be detected via Topological sort algorithm for example.

**Comment by cyc1ingsir** [comment]
How I solved the challenge within the project, I'm using kmapper in, in the end:

I've got this m:n relationship definition:
https://github.com/cetracker/cetrack-backend/blob/061aee8f03fbf51c4f54a69b2e25912e48229d0e/src/main/kotlin/de/cyclingsir/cetrack/part/storage/PartPartTypeRelationEntity.kt
which I try to map to these two objects within the domain layer.
https://github.com/cetracker/cetrack-backend/blob/061aee8f03fbf51c4f54a69b2e25912e48229d0e/src/main/kotlin/de/cyclingsir/cetrack/part/domain/DomainPart.kt
https://github.com/cetracker/cetrack-backend/blob/061aee8f03fbf51c4f54a69b2e25912e48229d0e/src/main/kotlin/de/cyclingsir/cetrack/part/domain/DomainPartType.kt

e.g. for the mapping 
https://github.com/cetracker/cetrack-backend/blob/061aee8f03fbf51c4f54a69b2e25912e48229d0e/src/main/kotlin/de/cyclingsir/cetrack/part/domain/PartTypeService.kt#L33-L36

To break this infinite loop, the complete mapping is done like this:

1) a mapping function (inside the main - injectable - mapper component):
https://github.com/cetracker/cetrack-backend/blob/061aee8f03fbf51c4f54a69b2e25912e48229d0e/src/main/kotlin/de/cyclingsir/cetrack/part/storage/Mapper.kt#L55-L57

2) the kmapper `@Mapper`
https://github.com/cetracker/cetrack-backend/blob/061aee8f03fbf51c4f54a69b2e25912e48229d0e/src/main/kotlin/de/cyclingsir/cetrack/part/storage/Mapper.kt#L28-L32

3) an a helper function using the above mapper and injecting an empty list to break the recursion
https://github.com/cetracker/cetrack-backend/blob/061aee8f03fbf51c4f54a69b2e25912e48229d0e/src/main/kotlin/de/cyclingsir/cetrack/part/storage/Mapper.kt#L66-L71

The above definition of this many to many relationship is similar to this one:
https://vladmihalcea.com/the-best-way-to-map-a-many-to-many-association-with-extra-columns-when-using-jpa-and-hibernate/
I've not looked into how JPA is handling this recursion. I suspect, it's some sort of lazy access.

A similar mapping logic is defined for mapping the objects from an to the REST layer.
REST <- mapping -> domain <- mapping -> storage

If one looks closely at the above described solution, one might notice, that this is done for both members of the relation as well as the object defining the relation. Each from and to the layer in question.

I was quite happy, to have come up with a solution where all the mapping code could be placed closely together as well as being able hide the mapping logic from the service where the mapping is needed, reducing it to a simple call like this: `partTypeEntities.map(mapper::map)`

**Comment by s0nicyouth** [comment]
Fixed
