### ISSUE TITLE
Name adjustement

### ISSUE THREAD

**Issue by jakoss** [s0nicyouth/kmapper#3]
Suggestion from my side - maybe the name kmapper isn't really that good for discoverability, because there already exists library with the same name doing (pretty much) the same thing: https://github.com/ProjectMapK/KMapper

Also - can you enable discussions on github, it might get helpful to cooperate in future. I'm already working on incorporating this library into our company patterns replacing MapStruct and i will definitely like to contribute in the future

**Comment by s0nicyouth** [comment]
@jakoss thanks for the advice about enabling discussions. I did that. The name adjustment might be moved there now I suppose so I'm closing this issue.
